server:
    port: 9090

logging:
    level:
        tk.mybatis: TRACE

druid:
    url: jdbc:oracle:thin:@192.168.2.244:1521:helowin
    username: STORAGE
    password: STORAGE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true


mybatis:
    type-aliases-package: com.antsoft.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.antsoft.database.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql